apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-html
  template:
    metadata:
      labels:
        app: simple-html
    spec:
      containers: 
        - name: nginx
          image: hav1s/simple-html:latest
          ports:
            - containerPort: 80
