apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
    containers:
      - name: simple-html-container
        image: hav1s/simple-html  
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-files
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: entrypoint-file
          mountPath: /usr/local/bin/entrypoint.sh
          subPath: entrypoint.sh
        command: ["/usr/local/bin/entrypoint.sh"]
        args: ["nginx", "-g", "daemon off;"]
    volumes:
      - name: app-files
        configMap:
          name: app-files-config
      - name: entrypoint-file
        configMap:
          name: entrypoint-config

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx-container
#         image: <your-docker-image>
#         ports:
#         - containerPort: 80
#         volumeMounts:
#         - name: app-files
#           mountPath: /usr/share/nginx/html
#           subPath: html
#         - name: entrypoint-file
#           mountPath: /usr/local/bin/entrypoint.sh
#           subPath: entrypoint.sh
#         command: ["/usr/local/bin/entrypoint.sh"]
#         args: ["nginx", "-g", "daemon off;"]
#       volumes:
#       - name: app-files
#         configMap:
#           name: app-files-config
#       - name: entrypoint-file
#         configMap:
#           name: entrypoint-config



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: simple-html-deployment
# spec:
#   replicas: 3
#   selector:
#     matchLa-html
#   template:bels:
#       app: nginx
#     metadata:
#       labels:
#         app: simple-html
#     spec:
#       containers: 
#         - name: nginx
#           image: hav1s/simple-html:v1
#           ports:
#             - containerPort: 80



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: simple-html-deployment
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: simple-html
#   template:
#     metadata:
#       labels:
#         app: simple-html
#     spec:
#       containers:
#       - name: simple-html
#         image: hav1s/simple-html:latest  # Ensure this is correct
#         ports:
#         - containerPort: 80
#         readinessProbe:                # Add readiness and liveness probes
#           httpGet:
#             path: /
#             port: 80
#           initialDelaySeconds: 5
#           periodSeconds: 10
#         livenessProbe:
#           httpGet:
#             path: /
#             port: 80
#           initialDelaySeconds: 15
#           periodSeconds: 20

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: simple-html-deployment
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: simple-html
#   template:
#     metadata:
#       labels:
#         app: simple-html
#     spec:
#       containers:
#       - name: simple-html
#         image: hav1s/simple-html:latest  # Ensure this matches the image in kustomization.yaml
#         ports:
#         - containerPort: 80
#         readinessProbe:                # Readiness probe example
#           httpGet:
#             path: /
#             port: 80
#           initialDelaySeconds: 5
#           periodSeconds: 10
#         livenessProbe:                 # Liveness probe example
#           httpGet:
#             path: /
#             port: 80
#           initialDelaySeconds: 15
#           periodSeconds: 20
