apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: hav1s/simple-html
    newName: hav1s/simple-html
    newTag: latest

