apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: hav1s/simple-html
    newName: hav1s/simple-html
    newTag: latest

