# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization

# resources:
#   - deployment.yaml
#   - service.yaml

# images:
#   - name: hav1s/simple-html
#     newName: hav1s/simple-html
#     newTag: latest


apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: simple-html-kustomization  # Define a unique name for the Kustomization resource
  namespace: default               # Specify the namespace

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: hav1s/simple-html
    newName: hav1s/simple-html
    newTag: latest


