# apiVersion: v1
# kind: Service
# metadata:
#   name: simple-html-service
# spec:
#   selector:
#     app: simple-html
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: simple-html-service
  labels:
    app: simple-html
spec:
  type: LoadBalancer
  selector:
    app: simple-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
