name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        sudo mv kustomize /usr/local/bin

    - name: Build and push Docker image
      run: |
        docker build -t hello-world-app:latest .
        docker tag hello-world-app:latest <YOUR_DOCKERHUB_USERNAME>/hello-world-app:latest
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push <YOUR_DOCKERHUB_USERNAME>/hello-world-app:latest

    - name: Deploy with Kustomize
      run: |
        kustomize build overlays/production | kubectl apply -f -
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
